# Generated by Django 5.2.5 on 2025-08-27 02:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchStats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='text',
            new_name='agent_name',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='text_1',
            new_name='customer_ID',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='value',
            new_name='invoice_price',
        ),
        migrations.AddField(
            model_name='stats',
            name='reward_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
