# Generated by Django 5.2.5 on 2025-08-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchStats', '0002_rename_text_stats_agent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='invoice_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stats',
            name='reward_points',
            field=models.IntegerField(default=1),
        ),
    ]
