# Generated by Django 5.2.5 on 2025-08-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchStats', '0003_alter_stats_invoice_price_alter_stats_reward_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='invoice_price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='stats',
            name='reward_points',
            field=models.IntegerField(default=''),
        ),
    ]
