# Generated by Django 5.2.5 on 2025-08-27 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchStats', '0005_alter_stats_invoice_price_alter_stats_reward_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='stats',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='stats',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
